$font = Cherry Bomb One

general {
    hide_cursor = true
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    color = rgba(0, 0, 0, 0)
}


# password input 
input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 3
    inner_color = rgba(0, 0, 0, 0.0) # no fill

    outer_color = rgba(255, 255, 255, 0.8) rgba(200, 200, 200, 0.7) 45deg

    check_color = rgba(255, 255, 255, 0.9) rgba(220, 220, 220, 0.7) 120deg

    fail_color = rgba(255, 77, 77, 0.9) rgba(200, 50, 50, 0.7) 40deg

    font_color = rgb(255, 255, 255)
    fade_on_empty = false
    rounding = 15

    font_family = $font
    placeholder_text = Input password...
    fail_text = $PAMFAIL

    dots_spacing = 0.3

    position = -80, -450
    halign = right
    valign = center
}


# TIME
label {
    monitor =
    text = $TIME # ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#variable-substitution
    font_size = 90
    font_family = $font

    position = -30, 0
    halign = right
    valign = top
}

# DATE
label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B %Y" # update every 60 seconds
    font_size = 25
    font_family = $font

    position = -30, -150
    halign = right
    valign = top
}
