# =========================
# Main
# =========================

[main]

font=JetBrainsMono Nerd Font Mono:size=24
dpi-aware=yes

# =========================
# Cursor
# =========================

[cursor]

style=underline
blink=yes

# =========================
# Colors — Transparent
# =========================

[colors-dark]

alpha=0.0

foreground=CAD3F5

selection-foreground=CAD3F5
selection-background=494D64